language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t l475ghost/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true l475ghost/react-test npm test

after_success:
  - docker build -t l475ghost/multi-client ./client
  - docker build -t l475ghost/multi-nginx ./nginx
  - docker build -t l475ghost/multi-server ./server
  - docker build -t l475ghost/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push l475ghost/multi-client
  - docker push l475ghost/multi-nginx
  - docker push l475ghost/multi-server
  - docker push l475ghost/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-950247871170
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
